version: "3"

services:
  api:
    build: .
    depends_on:
      - mongoinit
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongoinit:27017/gateway
      - APPLICATION_NAME=Share Your Idea
      - JWT_SECRET=myStrongPassword
      - CACHE_KEY=myStrongPassword
      - SWAGGER_DOC=swaggerPROD
    ports:
      - "5000:5000"
  mongo1:
    hostname: mongo1
    image: mongo
    expose:
      - 27017
    ports:
    - 27018:27017
    restart: always
    command: mongod --replSet my-mongo-set
  mongo2:
    hostname: mongo2
    image: mongo
    expose:
     - 27017
    ports:
      - 27019:27017
    restart: always
    command: mongod --replSet my-mongo-set

  mongoinit:
    image: mongo
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
    command: >
      mongo --host mongo1:27017 --eval
            '
            db = (new Mongo("localhost:27017")).getDB("gateway");
            config = {
            "_id" : "my-mongo-set",
            "members" : [
              {
                "_id" : 0,
                "host" : "mongo1:27017"
              },
              {
                "_id" : 1,
                "host" : "mongo2:27017"
              }
            ]
            };
            rs.initiate(config);
            rs.status();
            '
